development:
  adapter: postgresql
  encoding: unicode
  database: highlights_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: highlights_test
  pool: 5
  host: localhost

